send_sms/urls.py
#django
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'django.contrib.auth.views.login', name='Login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='Logout'),
    url(r'^send-sms/$', 'send_sms.views.sendSMS', name='Send SMS'),
    url(r'^messages/(?P<page>[0-9]+)$', 'send_sms.views.getMessages', name='Messages'),
    url(r'^contacts/(?P<page>[0-9]+)$', 'send_sms.views.viewContact', name='Contacts'),
    url(r'^contacts/edit/(?P<num>[0-9]+)$', 'send_sms.views.editContact', name='EditContact'),
    url(r'^contacts/edit-group/(?P<groupID>[0-9]+)$', 'send_sms.views.editGroup', name='EditGroup'),
    url(r'^contacts/delete/(?P<num>[0-9]+)$', 'send_sms.views.deleteContact', name='DeleteContact'),
    url(r'^contacts/group/delete/(?P<groupID>[0-9]+)$', 'send_sms.views.deleteGroup', name='DeleteContact'),
    url(r'^template/$', 'send_sms.views.createTemplate', name='CreateTemplate'),
    url(r'^template/(?P<templateID>[0-9]+)$', 'send_sms.views.editTemplate', name='EditTemplate'),
    url(r'^template/delete/(?P<templateID>[0-9]+)$', 'send_sms.views.deleteTemplate', name='DeleteTemplate'),
    url(r'^stats/$', 'send_sms.views.usageStats', name='UserStats'),
    url(r'^analytics/$', 'send_sms.views.analytics', name='Analytics'),
    # dans forum system
    url(r'^support/$', 'send_sms.views.support', name='Support'),
    # url(r'^sandbox/$',  'send_sms.views.sandbox', name='Login'),
)

sms_app/urls.py
#django
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('send_sms.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

send_sms/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class contacts(models.Model):
    user = models.ForeignKey(User)
    firstName = models.CharField("Prenom", max_length=20, null=False, blank=False)
    lastName = models.CharField("Nom de Famille", max_length=20, null=True, blank=True)
    phoneNumber = models.CharField("Numero de Telephone", max_length=8, null=True,)

    def __unicode__(self):
        return self.firstName+' '+self.lastName+' - '+self.phoneNumber


class device(models.Model):
    user = models.ForeignKey(User, default=0)
    deviceID = models.IntegerField()
    phoneNumber = models.CharField(max_length=8)
    accountEmail = models.CharField(max_length=30)
    accountPassword = models.CharField(max_length=30)

    def __unicode__(self):
        return self.user.username


class contactgroup(models.Model):
    user = models.ForeignKey(User)
    groupName = models.CharField("Nom du Groupe", max_length=50)
    contact = models.ManyToManyField(contacts)

    def __unicode__(self):
        return self.groupName


class msgTemplates(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField("Le Nom du Template", max_length=20)
    msgText = models.CharField("Modeles de Texte", max_length=160)

    def __unicode__(self):
        return self.name


class message(models.Model):
    user = models.ForeignKey(User)
    sentTo = models.CharField(max_length=50, null=False, blank=False)
    msgText = models.TextField(null=False, blank=False)

    def __unicode__(self):
        return self.user.username


USER_TYPES = ((0, 'Admin'), (1, 'Sub User'))
class userType(models.Model):
    user = models.ForeignKey(User)
    userType = models.IntegerField(choices=USER_TYPES, default=1)

    def __unicode__(self):
        return self.user.username

class adminUser(models.Model):
    masterUser = models.ForeignKey(User, related_name='Master')
    subUser = models.ManyToManyField(User, related_name='Sub')

    def __unicode__(self):
        return self.masterUser.username


#
# Dans upgrades
#
class fourmPost(models.Model):
    user = models.ForeignKey(User)
    date = models.DateField()
    message = models.TextField(null=False, blank=False)
    STATUT_CHOICES = (
        ('Resolu', 'Resolu'),
        ('En Cours', 'En Cours'),
    )
    statut = models.CharField(max_length=11, choices=STATUT_CHOICES, default='En Cours')

    def __unicode__(self):
        return self.user.username

class fourmResponse(models.Model):
    user = models.ForeignKey(User)
    date = models.DateField()
    message = models.TextField(null=False, blank=False)

    def __unicode__(self):
        return self.user.username

send_sms/forms.py
#django
from django import forms

#local
from django.forms import Textarea
from models import *

#lib


class AddContactForm(forms.ModelForm):
    class Meta:
        model = contacts
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(AddContactForm, self).__init__(*args, **kwargs)
        self.fields['firstName'].widget.attrs.update({'class': 'form-control'})
        self.fields['lastName'].widget.attrs.update({'class': 'form-control'})
        self.fields['phoneNumber'].widget.attrs.update({'class': 'form-control form-horizontal'})

class AddContactToGroupForm(forms.ModelForm):
    class Meta:
        model = contactgroup
        exclude = ['contact', 'user']

    def __init__(self, *args, **kwargs):
        super(AddContactToGroupForm, self).__init__(*args, **kwargs)
        self.fields['groupName'].widget.attrs.update({'class': 'form-control'})


class SendMsgForm(forms.Form):
    phoneNumber = forms.CharField(label="Numero de Telephone", required=True, widget=forms.TextInput(attrs={'class': "form-control"}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': "form-control"}))


class SaveMsgForm(forms.ModelForm):
    class Meta:
        model = message
        fields = '__all__'


class createTemplateForm(forms.ModelForm):
    class Meta:
        model = msgTemplates
        exclude = ['user']
        widgets = {
            'msgText': Textarea(),
        }

    def __init__(self, *args, **kwargs):
        super(createTemplateForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['msgText'].widget.attrs.update({'class': 'form-control', 'maxlength': '250'})
        

class fourmPostForm(forms.ModelForm):
    class Meta:
        model = fourmPost
        exclude = ['user', 'date', 'statut']

    def __init__(self, *args, **kwargs):
        super(fourmPostForm, self).__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({'class': 'form-control'})

send_sms/views.py
# -*- coding: utf8 -*- 
# django
from pprint import pprint
import user
from django.contrib import messages
from django.shortcuts import render_to_response, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.utils.html import escape


#lib
import json
import ast
import HTMLParser
import datetime
from text_unidecode import unidecode

#local
from functions import *
from models import contacts, contactgroup, device, User, msgTemplates, adminUser, message, userType, fourmPost, fourmResponse
from .forms import SendMsgForm, AddContactForm, AddContactToGroupForm, createTemplateForm, SaveMsgForm, fourmPostForm

# script for GSM7
#


@login_required
def sendSMS(request):
    form = SendMsgForm(request.POST or None)
    form2 = SaveMsgForm()
    gateway = SmsGateway()
    if form.is_valid():
        number = form.cleaned_data['phoneNumber']
        number_list = number.split(",")
        message3 = form.cleaned_data['message']
        message2 = unidecode(message3)
        message = message2.replace("'", " ")
        deviceID = request.POST.get('deviceID')
        device_obj = device.objects.all()
        for d_obj in device_obj:
            if d_obj.user == request.user:
                for num in number_list:
                    accountEmail = d_obj.accountEmail
                    accountPassword = d_obj.accountPassword
                    gateway.loginDetails(accountEmail, accountPassword)
                    gateway.sendMessageToNumber(num, message, deviceID)
                    save_it = form2.save(commit=False)
                    save_it.user = request.user
                    save_it.sentTo = num
                    save_it.msgText = message
                    save_it.save()
        messages.success(request, 'Message Envoye')
        return redirect('/messages/0')
    username = request.user.username
    device_obj = device.objects.all()
    contact_list = contacts.objects.filter(user=request.user).order_by('firstName')
    group_list = contactgroup.objects.filter(contact__user=request.user).distinct().order_by('groupName')
    template_list = msgTemplates.objects.filter(user=request.user).distinct()
    context = {"form": form}
    template = "sendsms.html"
    pg = ['active', '', '']
    return render_to_response(template, locals(), context_instance=RequestContext(request))


@login_required
def getMessages(request, page):
    device_obj = device.objects.filter(user=request.user)
    contact_obj = contacts.objects.filter(user=request.user)
    msgs = []
    for d_obj in device_obj:
        accountEmail = d_obj.accountEmail
        accountPassword = d_obj.accountPassword
        gateway = SmsGateway()
        gateway.loginDetails(accountEmail, accountPassword)
        json_string = gateway.getMessages()
    for msg in json_string['response']['result']:
        msg_encoded = HTMLParser.HTMLParser().unescape(msg['message'])
        if msg['status'] != 'manual send':
            msgs.append({
                "status": msg['status'],
                "sent_at": msg['sent_at'],
                "received_at": msg['received_at'],
                "contact_number": msg['contact']['number'],
                "message": msg_encoded})
    pagesize = 10
    pages = range(((len(msgs) - 1) / pagesize) + 1)
    active = int(page)
    msgs = msgs[(active * pagesize):(active * pagesize) + pagesize]
    pg = ['', 'active', '']
    return render_to_response('messages.html', locals(), context_instance=RequestContext(request))


@login_required
def viewContact(request, page):
    contact_list = contacts.objects.filter(user=request.user).order_by('firstName')
    form = AddContactForm(request.POST or None)
    if form.is_valid():
        save_it = form.save(commit=False)
        save_it.user = request.user
        save_it.save()
        messages.success(request, 'Contact Saved')
        return HttpResponseRedirect('')

    contact_group = contactgroup.objects.filter(user=request.user).order_by('groupName')
    groupForm = AddContactToGroupForm(request.POST or None)
    if groupForm.is_valid():
        cg = contactgroup()
        cg.user = request.user
        cg.groupName = groupForm.cleaned_data['groupName']
        checklist = request.POST.getlist('checks[]')
        cg.save()
        for num in checklist:
            c = contacts.objects.filter(user=request.user).get(phoneNumber=num)
            cg.contact.add(c)
        return HttpResponseRedirect('')
    active = int(page)
    pagesize = 10
    pages = range(((len(contact_list) - 1) / pagesize) + 1)
    contacts_pag = contact_list[active * pagesize: (active * pagesize) + pagesize]
    pg = ['', '', 'active']
    return render_to_response('contacts.html', locals(), context_instance=RequestContext(request))


@login_required
def editContact(request, num):
    contact = contacts.objects.filter(user=request.user).get(phoneNumber=num)
    form = AddContactForm(request.POST or None, instance=contact)
    if form.is_valid():
        save_it = form.save(commit=False)
        save_it.user = request.user
        save_it.save()
        return redirect('/contacts/0')
    return render_to_response('editcontact.html', locals(), context_instance=RequestContext(request))


@login_required
def deleteContact(request, num):
    contact = contacts.objects.filter(user=request.user).get(phoneNumber=num)
    contact.delete()
    return redirect('/contacts/0')


@login_required
def createTemplate(request):
    template = msgTemplates.objects.filter(user=request.user)
    form = createTemplateForm(request.POST or None)
    if form.is_valid():
        save_it = form.save(commit=False)
        save_it.user = request.user
        save_it.save()
        return redirect('/send-sms/')
    return render_to_response('createtemplate.html', locals(), context_instance=RequestContext(request))

@login_required
def editTemplate(request, templateID):
    template = msgTemplates.objects.filter(user=request.user).get(id=templateID)
    form = createTemplateForm(request.POST or None, instance=template)
    if form.is_valid():
        save_it = form.save(commit=False)
        save_it.user = request.user
        save_it.save()
        return redirect('/template/')
    return render_to_response('edittemplate.html', locals(), context_instance=RequestContext(request))

@login_required
def deleteTemplate(request, templateID):
    template = msgTemplates.objects.filter(user=request.user).get(id=templateID)
    template.delete()
    return redirect('/template/')

@login_required
def deleteGroup(request, groupID):
    group = contactgroup.objects.filter(user=request.user).get(id=groupID)
    group.delete()
    return redirect('/contacts/0')


@login_required
def editGroup(request, groupID):
    group = contactgroup.objects.filter(user=request.user).get(id=groupID)
    contact_list = contacts.objects.filter(user=request.user)
    form = AddContactToGroupForm(request.POST or None, instance=group)
    if form.is_valid():
        save_it = form.save(commit=False)
        save_it.user = request.user
        save_it.save()
        return redirect('/contacts/0')
    return render_to_response('editgroup.html', locals(), context_instance=RequestContext(request))


@login_required()
def usageStats(request):
    usrType = userType.objects.filter(user=request.user)
    for usr in usrType:
        if usr.id == request.user.id:
            if usr.userType == 1:
                return HttpResponseRedirect('/messages/0')
    msgs = []
    masterUsr = adminUser.objects.all()
    for usr in masterUsr:
        if usr.id == request.user.id:
            for subUsr in usr.subUser.all():
                subUsrMsgs = message.objects.filter(user=subUsr)
                numMsgs = len(subUsrMsgs)
                nested = []
                msgs.append(nested)
                for subUsrMsg in subUsrMsgs:
                    nested.append([subUsr.username,[subUsrMsg.sentTo, subUsrMsg.msgText], numMsgs])

    return render_to_response('stats.html', locals(), context_instance=RequestContext(request))


@login_required()
def analytics(request):
    phone = device.objects.filter(user=request.user)
    month = request.GET.get('month') or None
    year = request.GET.get('year') or None
    if 'month' in request.GET: 
        if month != None and year != None:
            month = int(month)
            year = int(year)
        for device_obj in phone:
            gateway = SmsGateway()
            accountEmail = device_obj.accountEmail
            accountPassword = device_obj.accountPassword
            gateway.loginDetails(accountEmail, accountPassword)
            json_string = gateway.getMessages()
            count = 0
            for msg in json_string['response']['result']:
                if msg['status'] == 'sent':
                    sentTime = datetime.datetime.fromtimestamp(msg['sent_at'])
                    if month==sentTime.month and year==sentTime.year:
                        count+=1
                        saving = count*96
            count_total = 0
            for msg in json_string['response']['result']:
                if msg['status'] == 'sent':
                    count_total+=1
                    saving_total = count_total*96
                
        return render_to_response('print_analytics.html', locals(), context_instance=RequestContext(request))
        
        
    return render_to_response('analytics.html', locals(), context_instance=RequestContext(request))

# @login_required
# def sandbox(request):
#     template = "sandbox.html"
#     return render_to_response(template, locals(), context_instance=RequestContext(request))


# Dans support forum for Faaa
@login_required
def support(request):

send_sms/templates/analytics.html
{% extends 'base.html' %}
{% block content %}
    <div class="row" style="padding-top:20px;">
        <div class="col-md-6">
            <div class="alert alert-info" role="alert">Obtenez des rapports statistiques précis de vos campagnes et des volumes de SMS envoyés. Choisissez un mois et une année ci-dessous et cliquez sur le bouton "Générer"</div></div>
        <div class="col-md-6"></div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <form action="" method="get">
                <p>
                <select class="form-control" name="month" id="month">
                    <option value="1">Janvier</option>
                    <option value="2">Février</option>
                    <option value="3">Mars</option>
                    <option value="4">Avril</option>
                    <option value="5">Mai</option>
                    <option value="6">Juin</option>
                    <option value="7">Juillet</option>
                    <option value="8">Août</option>
                    <option value="9">Septembre</option>
                    <option value="10">Octobre</option>
                    <option value="11">Novembre</option>
                    <option value="12">Décembre</option>
                </select>
                </p>
                <p>
                <select class="form-control" name="year" id="year">
                    <option value="2015" selected="true">2015</option>
{#                    <option value="2016">2016</option>#}
                </select>
                </p>
                <p>
                <input type="submit" class="form-control btn btn-lg btn-primary" value="Générer">
                </p>
            </form>
        </div>
        <div class="col-md-6"></div>
    </div>
{% endblock%}

send_sms/templates/contacts.html
{% extends "base.html" %}

<!-- THIS IS FOR SUCCESS MESSAGES -->
{% if messages %}
<div class="alert alert-success">
	<div class="container">
    	{% for message in messages %}
    		{{ message }}
   		{% endfor %}
   	</div>
</div>
{% endif %}
<!-- END THIS IS FOR SUCCESS MESSAGES -->

{% block content %}
    <h4>Mes Contacts</h4>
    <table class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th colspan="3">Liste des contacts</th>
        </tr>
        </thead>
        <tbody>
        {% for c in contacts_pag %}
            <tr>
                <td>{{ c.firstName }} {{ c.lastName }}</td>
                <td>{{ c.phoneNumber }}</td>
                <td><a href="/contacts/edit/{{c.phoneNumber}}" >Editer</a>/<a href="/contacts/delete/{{c.phoneNumber}}">Effacer</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination_messages">
    <ul class="pagination ct-blue">
        {% if active > 0 %}
        <li><a href="/contacts/{{active|add:'-1'}}">&laquo;</a></li>
        {% endif %}
{#        {% for p in pages %}#}
{#            {% if active == p %}#}
{#                <li class="active"><a href="/contacts/{{p}}">{{p|add:"1"}}</a></li>#}
{#            {% else %}#}
{#                <li><a href="/contacts/{{p}}">{{p|add:"1"}}</a></li>#}
{#            {% endif %}#}
{#        {% endfor %}#}
        {% if active < pages|length|add:'-1' %}
        <li><a href="/contacts/{{active|add:'1'}}">&raquo;</a></li>
        {% endif %}
    </ul>
    <hr />
    <br />
</div>
    <h4>Ajouter des contacts</h4>
     <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
    	<input type="submit" value="Ajouter Contact" class="btn btn-primary" />
    	<input type="reset"  value="Effacer" class="btn btn-danger" />
    </form>
    <br />
    <hr />
    <br />

    <h4>Groupes des contacts</h4>
    <table class="table table-bordered table-hover">
        <thead>
        	<tr>
           	 <th>Mes Groupes</th>
             <th>Membres</th>
             <th>Effacer</th>
        	</tr>
        </thead>
        <tbody>
        {% for cg in contact_group %}
            <tr>
                <td>{{ cg.groupName }}</td>
                    <td>{% for name in cg.contact.all %}{{name.firstName}} {{name.lastName}}, {% endfor %}</td>
                <td><a href="/contacts/group/delete/{{cg.id}}">Effacer</a> | <a href="/contacts/edit-group/{{cg.id}}">Editer</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br />
    <hr />
    <br />
    <form method="POST" action="">
        {% csrf_token %}
        {{ groupForm.as_p }}
            <select id="multiselect-contacts" multiple="multiple" name="checks[]">
                {% for contact in contact_list %}
                    <option value="{{ contact.phoneNumber }}">{{ contact.firstName }} {{ contact.lastName }}</option>
                {% endfor %}
            </select>
        <br />
        <br />
        <input type="submit" value="Ajouter Groupe" class="btn btn-primary" />
        <input type="reset" value="Effacer" class="btn btn-danger" />
    </form>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#multiselect-contacts').multiselect({
                nonSelectedText: 'Add Contacts',
                disableIfEmpty: true,
                maxHeight: 200,
                enableCaseInsensitiveFiltering: true
            });
        });
    </script>
{% endblock %}

send_sms/templates/createtemplate.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        <p><label>Nom</label>{{ form.name }}</p>
        <p><label>Message</label>{{ form.msgText }}</p>
        <div id="textarea_feedback" style="font-size:14px;color:#999999;"></div>
        <br />
    	<input type="submit" value="Enregistrer" class="btn btn-primary" />
    	<input type="reset"  value="Effacer" class="btn btn-danger" />
    </form>
    <br />
    <br />
    <table class="table table-bordered table-hover table-striped">
        <tr>
            <th>Nom</th>
            <th>Editer/Effacer</th>
        </tr>
        {% for t_obj in template  %}
            <tr>
                <td>{{ t_obj.name }}</td>
                <td><a href="/template/{{ t_obj.id }}">Editer</a>/<a href="/template/delete/{{ t_obj.id }}">Effacer</a></td>
            </tr>
        {% endfor %}
    </table>
    <script>
        $(document).ready(function() {
            var text_max = 250;
            $('#textarea_feedback').html(text_max + ' restant');
        
            $('#id_msgText').keyup(function() {
                var text_length = $('#id_msgText').val().length;
                var text_remaining = text_max - text_length;
        
                $('#textarea_feedback').html(text_remaining + ' restant');
            });
        });
    </script>
{% endblock %}

send_sms/templates/editcontact.html
{% extends "base.html" %}
{% block content %}
    <!-- THIS IS FOR SUCCESS MESSAGES -->
    {% if messages %}
    <div class="alert alert-success">
        <div class="container">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    </div>
    {% endif %}
    <!-- END THIS IS FOR SUCCESS MESSAGES -->
    <h4>Ajouter des contacts</h4>
     <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
    	<input type="submit" value="Sauvez" class="btn btn-primary" />
    	<input type="reset"  value="Effacer" class="btn btn-danger" />
    </form>
{% endblock %}

send_sms/templates/editgroup.html
{% extends "base.html" %}
{% block content %}
    <h4>Modifier le groupe</h4>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <select id="multiselect-contacts" multiple="multiple" name="checks[]">
            {% for contact in contact_list %}
                <option value="{{ contact.phoneNumber }}">{{ contact.firstName }} {{ contact.lastName }}</option>
            {% endfor %}
        </select>
    	<input type="submit" value="Sauvez" class="btn btn-primary" />
    	<input type="reset"  value="Effacer" class="btn btn-danger" />
    </form>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#multiselect-contacts').multiselect({
                nonSelectedText: 'Add Contacts',
                disableIfEmpty: true,
                maxHeight: 200,
                enableCaseInsensitiveFiltering: true
            });
        });
    </script>
{% endblock %}

send_sms/templates/edittemplate.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
    	<input type="submit" value="Enregistrer" class="btn btn-primary" />
    	<input type="reset"  value="Effacer" class="btn btn-danger" />
    </form>
{% endblock %}

send_sms/templates/sendsms.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="col-xs-12 col-sm-6 col-lg-8">
        <div class="alert alert-info" role="alert">Ajouter vos destinataires, écrivez votre message et cliquez sur le bouton "Envoyer"</div>
        <form method="POST" action="">
            {% csrf_token %}
            <p>{{ form.phoneNumber.label }}</p>
            <div class="">
                <input type="text" class="form-control" id="id_phoneNumber" name="phoneNumber" /><br />
                    <select class="form-control" id="contacts" multiple="multiple">
                        {% for c_obj in contact_list %}
                            <option value="{{ c_obj.phoneNumber }}">{{ c_obj.firstName }} {{ c_obj.lastName }}</option>
                        {% endfor %}
                    </select>
                    <select id="groups" size="2">
                        <label>Groups</label>
                        {% for g_obj in group_list %}
                                 <option value="[{% for obj in g_obj.contact.all %}<contacts: {{ obj.firstName }} {{ obj.lastName }} - {{ obj.phoneNumber }}>{%if not forloop.last%},{%endif%} {% endfor %}]">{{ g_obj.groupName }}</option>
                        {% endfor %}
                    </select><br /><br/>
                <p>{{ form.message.label }}</p>
                <textarea type="text" class="form-control" id="id_message" name="message" rows="10" maxlength="250" placeholder="Entrez votre message ou choisissez un template"></textarea>
                <div id="textarea_feedback" style="font-size:14px;color:#999999;"></div>
                <br />
               </div>
            <br>
            {% for d_obj in device_obj %}
                {% if username == d_obj.user.username %}
                    <input type="hidden" name="deviceID" id="id_deviceID" value="{{ d_obj.deviceID }}">
                {% endif %}
            {% endfor %}
            <div>
                <button class="btn btn-default dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-expanded="true">Templates<span class="caret"></span></button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                        <label>Templates</label>
                        {% for template in template_list %}
                            <li role="presentation">
                                <a href="#"  onclick="addtemplate('{{template.msgText}}')"
                                value="{{template.msgText}}" >{{template.name}}</a>
                            </li>
                        {% endfor %}
                        <label>Creer un Nouveau</label>
                        <li role="presentation">
                            <a href="/template/" class="list-group-item">Creer un Template</a>
                        </li>
                    </ul>
                <input type="submit" value="Envoyer" class="btn btn-primary">
            </div>
        </form>
        </div>
    <div class="col-xs-6 col-lg-4">
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#contacts').multiselect({
                nonSelectedText: 'Ajoutez Contact',
                disableIfEmpty: true,
                maxHeight: 200,
                buttonWidth: '220px',
                enableCaseInsensitiveFiltering: true
            });
            $('#groups').multiselect({
                nonSelectedText: 'Ajoutez Groupe',
                disableIfEmpty: true,
                maxHeight: 200
            });
            var clist = [];
            $("#contacts").change(function(e){
                var selected = $(e.target).val()
                if (selected == null){
                    $('#id_phoneNumber').removeTag(clist[0]);
                    list = [];
                }else {
                    for (var i = 0; i < clist.length; i++){
                        $('#id_phoneNumber').removeTag(clist[i]);
                    }
                    for (var i = 0; i < selected.length; i++){
                        $('#id_phoneNumber').addTag(selected[i])
                    }
                    clist = selected;
                }
            })
            var glist = [];
            $("#groups").change(function(e){
                var selected = $(e.target).val()
                selected = selected.split(', ')
                for (var i = 0; i < glist.length; i++){
                    $('#id_phoneNumber').removeTag(glist[i]);
                }
                glist = []
                for (var i = 0; i < selected.length; i++){
                    var num = parseInt(selected[i].split(' - ')[1]);
                    glist = glist.concat([num]);
                    $('#id_phoneNumber').addTag(num);
                }
            })
            $('#id_phoneNumber').tagsInput({
                'width': '400px',
                'height': '80px',
                'defaultText': ''
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            var text_max = 250;
            $('#textarea_feedback').html(text_max + ' restant');
        
            $('#id_message').keyup(function() {
                var text_length = $('#id_message').val().length;
                var text_remaining = text_max - text_length;
        
                $('#textarea_feedback').html(text_remaining + ' restant');
            });
        });
    </script>
{% endblock %}

send_sms/templates/stats.html
{% extends 'base.html' %}
{% block content %}
    {% for subusr in msgs %}
        <p>Messages sent from <b>{{ subusr.1.0}}'s</b> Account</p>
        <p>Total msgs sent {{ subusr.1.2 }}</p>
        <table class="table table-bordered table-hover table-striped">
            <tr>
                <th>To</th>
                <th>Message</th>
            </tr>
            {% for msg in subusr %}
                    <tr>
                        <td>{{ msg.1.0 }}</td>
                        <td>{{ msg.1.1 }}</td>
                    </tr>
            {% endfor %}
        </table>
    {% endfor %}
{#    {% debug %}#}
{% endblock %}